import React, { useEffect, useState } from "react";
import Dropdown from "../dropDown/dropDown";
import { FaMinus, FaPlus } from "react-icons/fa";
import { Info as InfoIcon } from "@mui/icons-material";

interface BookingSectionCartProps {
  propertySize: string;
  setPropertySize: (size: string) => void;
  numCleaners: string;
  setNumCleaners: (num: string) => void;
  duration: string;
  setDuration: (duration: string) => void;
  propertyType: string;
  setPropertyType: (type: string) => void;
  contactType: string;
  setContactType: (contactType: string) => void;
  language: string;
  setLanguage: (language: string) => void;
  onBasePriceChange: (maxTime: number) => void;
}

const BookingSectionCart: React.FC<BookingSectionCartProps> = ({
  propertySize,
  setPropertySize,
  numCleaners,
  setNumCleaners,
  duration,
  setDuration,
  propertyType,
  setPropertyType,
  contactType,
  setContactType,
  language,
  setLanguage,
  onBasePriceChange,
}) => {
  const [autoGeneratedCleaners, setAutoGeneratedCleaners] = useState<number>(1);
  const [isPropertySizeSelected, setIsPropertySizeSelected] =
    useState<boolean>(false);
  const [isManualCleanerChange, setIsManualCleanerChange] = useState(false);

  const propertyTypeOptions = [
    { value: "home", label: "Home" },
    { value: "apartment", label: "Apartment" },
    { value: "villa", label: "Villa" },
    { value: "commercial property", label: "Commercial property" },
    { value: "government office", label: "Government office" },
    { value: "public office", label: "Public office" },
    { value: "private office", label: "Private office " },
    { value: "daycare centre", label: "Daycare centre " },
    { value: "elders care centre", label: "Elder's Care Centre" },
    { value: "shopping mall", label: "Shopping mall" },
    { value: "government hospital", label: "Government hospital" },
    { value: "private hospital", label: "Private hospital" },
    { value: "sport centre", label: "Sport centre" },
    { value: "gym", label: "Gym " },
    { value: "restaurant", label: "Restaurant" },
    { value: "hotel", label: "Hotel" },
    {
      value: "school private or government",
      label: "School Private or Government",
    },
    { value: "transport sector", label: "Transport sector" },
    { value: "airport", label: "Airport" },
    { value: "retail building or shop", label: "Retail building or shop" },
    { value: "other", label: "Other sector" },
  ];

  const contactTypeOptions = [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
  ];

  const languageOptions = [
    { value: "english", label: "English" },
    { value: "french", label: "French" },
    { value: "spanish", label: "Spanish" },
    { value: "Dutch", label: "Dutch" },
    { value: "German", label: "German" },
    { value: "Arabic", label: "Arabic" },
  ];

  // Predefined durations
  const durationMapping: Record<string, { minTime: number; maxTime: number }> =
    {
      "20m²(215ft²)": { minTime: 2.5, maxTime: 3.0 },
      "21m²(226ft²)": { minTime: 2.5, maxTime: 3.0 },
      "22m²(237ft²)": { minTime: 2.5, maxTime: 3.0 },
      "23m²(248ft²)": { minTime: 2.5, maxTime: 3.0 },
      "24m²(258ft²)": { minTime: 2.5, maxTime: 3.0 },
      "25m²(269ft²)": { minTime: 2.5, maxTime: 3.0 },
      "26m²(280ft²)": { minTime: 2.5, maxTime: 3.0 },
      "27m²(291ft²)": { minTime: 2.5, maxTime: 3.0 },
      "28m²(301ft²)": { minTime: 2.5, maxTime: 3.0 },
      "29m²(312ft²)": { minTime: 2.5, maxTime: 3.0 },
      "30m²(323ft²)": { minTime: 2.5, maxTime: 3.0 },
      "31m²(334ft²)": { minTime: 2.5, maxTime: 3.0 },
      "32m²(344ft²)": { minTime: 2.5, maxTime: 3.0 },
      "33m²(355ft²)": { minTime: 2.5, maxTime: 3.0 },
      "34m²(365ft²)": { minTime: 2.5, maxTime: 3.0 },
      "35m²(376ft²)": { minTime: 2.5, maxTime: 3.0 },
      "36m²(387ft²)": { minTime: 2.5, maxTime: 3.0 },
      "37m²(398ft²)": { minTime: 2.5, maxTime: 3.0 },
      "38m²(409ft²)": { minTime: 2.5, maxTime: 3.0 },
      "39m²(419ft²)": { minTime: 2.5, maxTime: 3.0 },
      "40m²(431ft²)": { minTime: 2.5, maxTime: 3.0 },
      "41m²(442ft²)": { minTime: 2.5, maxTime: 3.0 },
      "42m²(452ft²)": { minTime: 2.5, maxTime: 3.0 },
      "43m²(463ft²)": { minTime: 2.5, maxTime: 3.0 },
      "44m²(474ft²)": { minTime: 2.5, maxTime: 3.0 },
      "45m²(484ft²)": { minTime: 2.5, maxTime: 3.0 },
      "46m²(495ft²)": { minTime: 2.5, maxTime: 3.0 },
      "47m²(506ft²)": { minTime: 2.5, maxTime: 3.0 },
      "48m²(517ft²)": { minTime: 2.5, maxTime: 3.0 },
      "49m²(528ft²)": { minTime: 2.5, maxTime: 3.0 },
      "50m²(538ft²)": { minTime: 3.0, maxTime: 4.0 },
      "51m²(549ft²)": { minTime: 3.0, maxTime: 4.0 },
      "52m²(560ft²)": { minTime: 3.0, maxTime: 4.0 },
      "53m²(570ft²)": { minTime: 3.0, maxTime: 4.0 },
      "54m²(581ft²)": { minTime: 3.0, maxTime: 4.0 },
      "55m²(592ft²)": { minTime: 3.0, maxTime: 4.0 },
      "56m²(603ft²)": { minTime: 3.0, maxTime: 4.0 },
      "57m²(613ft²)": { minTime: 3.0, maxTime: 4.0 },
      "58m²(624ft²)": { minTime: 3.0, maxTime: 4.0 },
      "59m²(635ft²)": { minTime: 3.0, maxTime: 4.0 },
      "60m²(646ft²)": { minTime: 3.0, maxTime: 4.0 },
      "61m²(656ft²)": { minTime: 3.0, maxTime: 4.0 },
      "62m²(667ft²)": { minTime: 3.0, maxTime: 4.0 },
      "63m²(678ft²)": { minTime: 3.0, maxTime: 4.0 },
      "64m²(689ft²)": { minTime: 3.0, maxTime: 4.0 },
      "65m²(699ft²)": { minTime: 3.0, maxTime: 4.0 },
      "66m²(710ft²)": { minTime: 3.0, maxTime: 4.0 },
      "67m²(721ft²)": { minTime: 3.0, maxTime: 4.0 },
      "68m²(732ft²)": { minTime: 3.0, maxTime: 4.0 },
      "69m²(742ft²)": { minTime: 3.0, maxTime: 4.0 },
      "70m²(753ft²)": { minTime: 3.0, maxTime: 4.0 },
      "71m²(764ft²)": { minTime: 3.0, maxTime: 4.0 },
      "72m²(775ft²)": { minTime: 3.0, maxTime: 4.0 },
      "73m²(785ft²)": { minTime: 3.0, maxTime: 4.0 },
      "74m²(796ft²)": { minTime: 3.0, maxTime: 4.0 },
      "75m²(807ft²)": { minTime: 4.0, maxTime: 5.5 },
      "76m²(818ft²)": { minTime: 4.0, maxTime: 5.5 },
      "77m²(829ft²)": { minTime: 4.0, maxTime: 5.5 },
      "78m²(840ft²)": { minTime: 4.0, maxTime: 5.5 },
      "79m²(850ft²)": { minTime: 4.0, maxTime: 5.5 },
      "80m²(861ft²)": { minTime: 4.0, maxTime: 5.5 },
      "81m²(872ft²)": { minTime: 4.0, maxTime: 5.5 },
      "82m²(883ft²)": { minTime: 4.0, maxTime: 5.5 },
      "83m²(893ft²)": { minTime: 4.0, maxTime: 5.5 },
      "84m²(904ft²)": { minTime: 4.0, maxTime: 5.5 },
      "85m²(915ft²)": { minTime: 4.0, maxTime: 5.5 },
      "86m²(926ft²)": { minTime: 4.0, maxTime: 5.5 },
      "87m²(937ft²)": { minTime: 4.0, maxTime: 5.5 },
      "88m²(947ft²)": { minTime: 4.0, maxTime: 5.5 },
      "89m²(958ft²)": { minTime: 4.0, maxTime: 5.5 },
      "90m²(969ft²)": { minTime: 4.0, maxTime: 5.5 },
      "91m²(980ft²)": { minTime: 4.0, maxTime: 5.5 },
      "92m²(990ft²)": { minTime: 4.0, maxTime: 5.5 },
      "93m²(1001ft²)": { minTime: 4.0, maxTime: 5.5 },
      "94m²(1012ft²)": { minTime: 4.0, maxTime: 5.5 },
      "95m²(1023ft²)": { minTime: 4.0, maxTime: 5.5 },
      "96m²(1033ft²)": { minTime: 4.0, maxTime: 5.5 },
      "97m²(1044ft²)": { minTime: 4.0, maxTime: 5.5 },
      "98m²(1055ft²)": { minTime: 4.0, maxTime: 5.5 },
      "99m²(1066ft²)": { minTime: 4.0, maxTime: 5.5 },
      "100m²(1076ft²)": { minTime: 5.5, maxTime: 6.5 },
      "101m²(1087ft²)": { minTime: 5.5, maxTime: 6.5 },
      "102m²(1098ft²)": { minTime: 5.5, maxTime: 6.5 },
      "103m²(1109ft²)": { minTime: 5.5, maxTime: 6.5 },
      "104m²(1119ft²)": { minTime: 5.5, maxTime: 6.5 },
      "105m²(1130ft²)": { minTime: 5.5, maxTime: 6.5 },
      "106m²(1141ft²)": { minTime: 5.5, maxTime: 6.5 },
      "107m²(1152ft²)": { minTime: 5.5, maxTime: 6.5 },
      "108m²(1162ft²)": { minTime: 5.5, maxTime: 6.5 },
      "109m²(1173ft²)": { minTime: 5.5, maxTime: 6.5 },
      "110m²(1184ft²)": { minTime: 5.5, maxTime: 6.5 },
      "111m²(1195ft²)": { minTime: 5.5, maxTime: 6.5 },
      "112m²(1205ft²)": { minTime: 5.5, maxTime: 6.5 },
      "113m²(1216ft²)": { minTime: 5.5, maxTime: 6.5 },
      "114m²(1227ft²)": { minTime: 5.5, maxTime: 6.5 },
      "115m²(1238ft²)": { minTime: 5.5, maxTime: 6.5 },
      "116m²(1248ft²)": { minTime: 5.5, maxTime: 6.5 },
      "117m²(1259ft²)": { minTime: 5.5, maxTime: 6.5 },
      "118m²(1270ft²)": { minTime: 5.5, maxTime: 6.5 },
      "119m²(1281ft²)": { minTime: 5.5, maxTime: 6.5 },
      "120m²(1291ft²)": { minTime: 5.5, maxTime: 6.5 },
      "121m²(1302ft²)": { minTime: 5.5, maxTime: 6.5 },
      "122m²(1313ft²)": { minTime: 5.5, maxTime: 6.5 },
      "123m²(1324ft²)": { minTime: 5.5, maxTime: 6.5 },
      "124m²(1334ft²)": { minTime: 5.5, maxTime: 6.5 },
      "125m²(1345ft²)": { minTime: 6.5, maxTime: 7.5 },
      "126m²(1356ft²)": { minTime: 6.5, maxTime: 7.5 },
      "127m²(1367ft²)": { minTime: 6.5, maxTime: 7.5 },
      "128m²(1378ft²)": { minTime: 6.5, maxTime: 7.5 },
      "129m²(1388ft²)": { minTime: 6.5, maxTime: 7.5 },
      "130m²(1399ft²)": { minTime: 6.5, maxTime: 7.5 },
      "131m²(1410ft²)": { minTime: 6.5, maxTime: 7.5 },
      "132m²(1421ft²)": { minTime: 6.5, maxTime: 7.5 },
      "133m²(1432ft²)": { minTime: 6.5, maxTime: 7.5 },
      "134m²(1442ft²)": { minTime: 6.5, maxTime: 7.5 },
      "135m²(1453ft²)": { minTime: 6.5, maxTime: 7.5 },
      "136m²(1464ft²)": { minTime: 6.5, maxTime: 7.5 },
      "137m²(1475ft²)": { minTime: 6.5, maxTime: 7.5 },
      "138m²(1485ft²)": { minTime: 6.5, maxTime: 7.5 },
      "139m²(1496ft²)": { minTime: 6.5, maxTime: 7.5 },
      "140m²(1507ft²)": { minTime: 6.5, maxTime: 7.5 },
      "141m²(1518ft²)": { minTime: 6.5, maxTime: 7.5 },
      "142m²(1528ft²)": { minTime: 6.5, maxTime: 7.5 },
      "143m²(1539ft²)": { minTime: 6.5, maxTime: 7.5 },
      "144m²(1550ft²)": { minTime: 6.5, maxTime: 7.5 },
      "145m²(1561ft²)": { minTime: 6.5, maxTime: 7.5 },
      "146m²(1572ft²)": { minTime: 6.5, maxTime: 7.5 },
      "147m²(1582ft²)": { minTime: 6.5, maxTime: 7.5 },
      "148m²(1593ft²)": { minTime: 6.5, maxTime: 7.5 },
      "149m²(1604ft²)": { minTime: 6.5, maxTime: 7.5 },
      "150m²(1615ft²)": { minTime: 7.5, maxTime: 9.0 },
      "151m²(1625ft²)": { minTime: 7.5, maxTime: 9.0 },
      "152m²(1636ft²)": { minTime: 7.5, maxTime: 9.0 },
      "153m²(1647ft²)": { minTime: 7.5, maxTime: 9.0 },
      "154m²(1658ft²)": { minTime: 7.5, maxTime: 9.0 },
      "155m²(1668ft²)": { minTime: 7.5, maxTime: 9.0 },
      "156m²(1679ft²)": { minTime: 7.5, maxTime: 9.0 },
      "157m²(1690ft²)": { minTime: 7.5, maxTime: 9.0 },
      "158m²(1701ft²)": { minTime: 7.5, maxTime: 9.0 },
      "159m²(1711ft²)": { minTime: 7.5, maxTime: 9.0 },
      "160m²(1722ft²)": { minTime: 7.5, maxTime: 9.0 },
      "161m²(1733ft²)": { minTime: 7.5, maxTime: 9.0 },
      "162m²(1744ft²)": { minTime: 7.5, maxTime: 9.0 },
      "163m²(1754ft²)": { minTime: 7.5, maxTime: 9.0 },
      "164m²(1765ft²)": { minTime: 7.5, maxTime: 9.0 },
      "165m²(1776ft²)": { minTime: 7.5, maxTime: 9.0 },
      "166m²(1787ft²)": { minTime: 7.5, maxTime: 9.0 },
      "167m²(1797ft²)": { minTime: 7.5, maxTime: 9.0 },
      "168m²(1808ft²)": { minTime: 7.5, maxTime: 9.0 },
      "169m²(1819ft²)": { minTime: 7.5, maxTime: 9.0 },
      "170m²(1830ft²)": { minTime: 7.5, maxTime: 9.0 },
      "171m²(1840ft²)": { minTime: 7.5, maxTime: 9.0 },
      "172m²(1851ft²)": { minTime: 7.5, maxTime: 9.0 },
      "173m²(1862ft²)": { minTime: 7.5, maxTime: 9.0 },
      "174m²(1873ft²)": { minTime: 7.5, maxTime: 9.0 },
      "175m²(1883ft²)": { minTime: 7.5, maxTime: 9.0 },
      "176m²(1894ft²)": { minTime: 7.5, maxTime: 9.0 },
      "177m²(1905ft²)": { minTime: 7.5, maxTime: 9.0 },
      "178m²(1916ft²)": { minTime: 7.5, maxTime: 9.0 },
      "179m²(1926ft²)": { minTime: 7.5, maxTime: 9.0 },
      "180m²(1937ft²)": { minTime: 7.5, maxTime: 9.0 },
      "181m²(1948ft²)": { minTime: 7.5, maxTime: 9.0 },
      "182m²(1959ft²)": { minTime: 7.5, maxTime: 9.0 },
      "183m²(1969ft²)": { minTime: 7.5, maxTime: 9.0 },
      "184m²(1980ft²)": { minTime: 7.5, maxTime: 9.0 },
      "185m²(1991ft²)": { minTime: 7.5, maxTime: 9.0 },
      "186m²(2002ft²)": { minTime: 7.5, maxTime: 9.0 },
      "187m²(2012ft²)": { minTime: 7.5, maxTime: 9.0 },
      "188m²(2023ft²)": { minTime: 7.5, maxTime: 9.0 },
      "189m²(2034ft²)": { minTime: 7.5, maxTime: 9.0 },
      "190m²(2045ft²)": { minTime: 7.5, maxTime: 9.0 },
      "191m²(2055ft²)": { minTime: 7.5, maxTime: 9.0 },
      "192m²(2066ft²)": { minTime: 7.5, maxTime: 9.0 },
      "193m²(2077ft²)": { minTime: 7.5, maxTime: 9.0 },
      "194m²(2088ft²)": { minTime: 7.5, maxTime: 9.0 },
      "195m²(2098ft²)": { minTime: 7.5, maxTime: 9.0 },
      "196m²(2109ft²)": { minTime: 7.5, maxTime: 9.0 },
      "197m²(2120ft²)": { minTime: 7.5, maxTime: 9.0 },
      "198m²(2131ft²)": { minTime: 7.5, maxTime: 9.0 },
      "199m²(2141ft²)": { minTime: 7.5, maxTime: 9.0 },
      "200m²(2153ft²)": { minTime: 9.0, maxTime: 10.5 },
      "201m²(2164ft²)": { minTime: 9.0, maxTime: 10.5 },
      "202m²(2174ft²)": { minTime: 9.0, maxTime: 10.5 },
      "203m²(2185ft²)": { minTime: 9.0, maxTime: 10.5 },
      "204m²(2196ft²)": { minTime: 9.0, maxTime: 10.5 },
      "205m²(2207ft²)": { minTime: 9.0, maxTime: 10.5 },
      "206m²(2217ft²)": { minTime: 9.0, maxTime: 10.5 },
      "207m²(2228ft²)": { minTime: 9.0, maxTime: 10.5 },
      "208m²(2239ft²)": { minTime: 9.0, maxTime: 10.5 },
      "209m²(2250ft²)": { minTime: 9.0, maxTime: 10.5 },
      "210m²(2260ft²)": { minTime: 9.0, maxTime: 10.5 },
      "211m²(2271ft²)": { minTime: 9.0, maxTime: 10.5 },
      "212m²(2282ft²)": { minTime: 9.0, maxTime: 10.5 },
      "213m²(2293ft²)": { minTime: 9.0, maxTime: 10.5 },
      "214m²(2303ft²)": { minTime: 9.0, maxTime: 10.5 },
      "215m²(2314ft²)": { minTime: 9.0, maxTime: 10.5 },
      "216m²(2325ft²)": { minTime: 9.0, maxTime: 10.5 },
      "217m²(2336ft²)": { minTime: 9.0, maxTime: 10.5 },
      "218m²(2346ft²)": { minTime: 9.0, maxTime: 10.5 },
      "219m²(2357ft²)": { minTime: 9.0, maxTime: 10.5 },
      "220m²(2368ft²)": { minTime: 9.0, maxTime: 10.5 },
      "221m²(2379ft²)": { minTime: 9.0, maxTime: 10.5 },
      "222m²(2389ft²)": { minTime: 9.0, maxTime: 10.5 },
      "223m²(2400ft²)": { minTime: 9.0, maxTime: 10.5 },
      "224m²(2411ft²)": { minTime: 9.0, maxTime: 10.5 },
      "225m²(2422ft²)": { minTime: 10.5, maxTime: 12.0 },
      "226m²(2427ft²)": { minTime: 10.5, maxTime: 12.0 },
      "227m²(2440ft²)": { minTime: 10.5, maxTime: 12.0 },
      "228m²(2448ft²)": { minTime: 10.5, maxTime: 12.0 },
      "229m²(2460ft²)": { minTime: 10.5, maxTime: 12.0 },
      "230m²(2476ft²)": { minTime: 10.5, maxTime: 12.0 },
      "231m²(2480ft²)": { minTime: 10.5, maxTime: 12.0 },
      "232m²(2490ft²)": { minTime: 10.5, maxTime: 12.0 },
      "233m²(2500ft²)": { minTime: 10.5, maxTime: 12.0 },
      "234m²(2520ft²)": { minTime: 10.5, maxTime: 12.0 },
      "235m²(2535ft²)": { minTime: 10.5, maxTime: 12.0 },
      "236m²(2545ft²)": { minTime: 10.5, maxTime: 12.0 },
      "237m²(2550ft²)": { minTime: 10.5, maxTime: 12.0 },
      "238m²(2565ft²)": { minTime: 10.5, maxTime: 12.0 },
      "239m²(2570ft²)": { minTime: 10.5, maxTime: 12.0 },
      "240m²(2585ft²)": { minTime: 10.5, maxTime: 12.0 },
      "241m²(2595ft²)": { minTime: 10.5, maxTime: 12.0 },
      "242m²(2610ft²)": { minTime: 10.5, maxTime: 12.0 },
      "243m²(2620ft²)": { minTime: 10.5, maxTime: 12.0 },
      "244m²(2635ft²)": { minTime: 10.5, maxTime: 12.0 },
      "245m²(2640ft²)": { minTime: 10.5, maxTime: 12.0 },
      "246m²(2650ft²)": { minTime: 10.5, maxTime: 12.0 },
      "247m²(2665ft²)": { minTime: 10.5, maxTime: 12.0 },
      "248m²(2675ft²)": { minTime: 10.5, maxTime: 12.0 },
      "249m²(2685ft²)": { minTime: 10.5, maxTime: 12.0 },
      "250m²(2690ft²)": { minTime: 12.0, maxTime: 13.5 },
      "251m²(2701ft²)": { minTime: 12.0, maxTime: 13.5 },
      "252m²(2710ft²)": { minTime: 12.0, maxTime: 13.5 },
      "253m²(2720ft²)": { minTime: 12.0, maxTime: 13.5 },
      "254m²(2730ft²)": { minTime: 12.0, maxTime: 13.5 },
      "255m²(2740ft²)": { minTime: 12.0, maxTime: 13.5 },
      "256m²(2750ft²)": { minTime: 12.0, maxTime: 13.5 },
      "257m²(2760ft²)": { minTime: 12.0, maxTime: 13.5 },
      "258m²(2770ft²)": { minTime: 12.0, maxTime: 13.5 },
      "259m²(2780ft²)": { minTime: 12.0, maxTime: 13.5 },
      "260m²(2790ft²)": { minTime: 12.0, maxTime: 13.5 },
      "261m²(2800ft²)": { minTime: 12.0, maxTime: 13.5 },
      "262m²(2810ft²)": { minTime: 12.0, maxTime: 13.5 },
      "263m²(2820ft²)": { minTime: 12.0, maxTime: 13.5 },
      "264m²(2830ft²)": { minTime: 12.0, maxTime: 13.5 },
      "265m²(2840ft²)": { minTime: 12.0, maxTime: 13.5 },
      "266m²(2850ft²)": { minTime: 12.0, maxTime: 13.5 },
      "267m²(2860ft²)": { minTime: 12.0, maxTime: 13.5 },
      "268m²(2870ft²)": { minTime: 12.0, maxTime: 13.5 },
      "269m²(2880ft²)": { minTime: 12.0, maxTime: 13.5 },
      "270m²(2890ft²)": { minTime: 12.0, maxTime: 13.5 },
      "271m²(2900ft²)": { minTime: 12.0, maxTime: 13.5 },
      "272m²(2910ft²)": { minTime: 12.0, maxTime: 13.5 },
      "273m²(2920ft²)": { minTime: 12.0, maxTime: 13.5 },
      "274m²(2930ft²)": { minTime: 12.0, maxTime: 13.5 },
      "275m²(2960ft²)": { minTime: 13.5, maxTime: 15.5 },
      "276m²(2970ft²)": { minTime: 13.5, maxTime: 15.5 },
      "277m²(2980ft²)": { minTime: 13.5, maxTime: 15.5 },
      "278m²(2990ft²)": { minTime: 13.5, maxTime: 15.5 },
      "279m²(3000ft²)": { minTime: 13.5, maxTime: 15.5 },
      "280m²(3010ft²)": { minTime: 13.5, maxTime: 15.5 },
      "281m²(3020ft²)": { minTime: 13.5, maxTime: 15.5 },
      "282m²(3030ft²)": { minTime: 13.5, maxTime: 15.5 },
      "283m²(3040ft²)": { minTime: 13.5, maxTime: 15.5 },
      "284m²(3050ft²)": { minTime: 13.5, maxTime: 15.5 },
      "285m²(3060ft²)": { minTime: 13.5, maxTime: 15.5 },
      "286m²(3070ft²)": { minTime: 13.5, maxTime: 15.5 },
      "287m²(3080ft²)": { minTime: 13.5, maxTime: 15.5 },
      "288m²(3090ft²)": { minTime: 13.5, maxTime: 15.5 },
      "289m²(3100ft²)": { minTime: 13.5, maxTime: 15.5 },
      "290m²(3110ft²)": { minTime: 13.5, maxTime: 15.5 },
      "291m²(3120ft²)": { minTime: 13.5, maxTime: 15.5 },
      "292m²(3130ft²)": { minTime: 13.5, maxTime: 15.5 },
      "293m²(3140ft²)": { minTime: 13.5, maxTime: 15.5 },
      "294m²(3150ft²)": { minTime: 13.5, maxTime: 15.5 },
      "295m²(3160ft²)": { minTime: 13.5, maxTime: 15.5 },
      "296m²(3170ft²)": { minTime: 13.5, maxTime: 15.5 },
      "297m²(3180ft²)": { minTime: 13.5, maxTime: 15.5 },
      "298m²(3190ft²)": { minTime: 13.5, maxTime: 15.5 },
      "299m²(3200ft²)": { minTime: 13.5, maxTime: 15.5 },
      "300m²(3229ft²)": { minTime: 15.5, maxTime: 17.0 },
      "301m²(3237ft²)": { minTime: 15.5, maxTime: 17.0 },
      "302m²(3249ft²)": { minTime: 15.5, maxTime: 17.0 },
      "303m²(3257ft²)": { minTime: 15.5, maxTime: 17.0 },
      "304m²(3268ft²)": { minTime: 15.5, maxTime: 17.0 },
      "305m²(3276ft²)": { minTime: 15.5, maxTime: 17.0 },
      "306m²(3286ft²)": { minTime: 15.5, maxTime: 17.0 },
      "307m²(3295ft²)": { minTime: 15.5, maxTime: 17.0 },
      "308m²(3305ft²)": { minTime: 15.5, maxTime: 17.0 },
      "309m²(3314ft²)": { minTime: 15.5, maxTime: 17.0 },
      "310m²(3323ft²)": { minTime: 15.5, maxTime: 17.0 },
      "311m²(3332ft²)": { minTime: 15.5, maxTime: 17.0 },
      "312m²(3342ft²)": { minTime: 15.5, maxTime: 17.0 },
      "313m²(3351ft²)": { minTime: 15.5, maxTime: 17.0 },
      "314m²(3361ft²)": { minTime: 15.5, maxTime: 17.0 },
      "315m²(3370ft²)": { minTime: 15.5, maxTime: 17.0 },
      "316m²(3380ft²)": { minTime: 15.5, maxTime: 17.0 },
      "317m²(3389ft²)": { minTime: 15.5, maxTime: 17.0 },
      "318m²(3399ft²)": { minTime: 15.5, maxTime: 17.0 },
      "319m²(3408ft²)": { minTime: 15.5, maxTime: 17.0 },
      "320m²(3417ft²)": { minTime: 15.5, maxTime: 17.0 },
      "321m²(3427ft²)": { minTime: 15.5, maxTime: 17.0 },
      "322m²(3436ft²)": { minTime: 15.5, maxTime: 17.0 },
      "323m²(3446ft²)": { minTime: 15.5, maxTime: 17.0 },
      "324m²(3455ft²)": { minTime: 15.5, maxTime: 17.0 },
      "325m²(3498ft²)": { minTime: 17.0, maxTime: 19.0 },
      "326m²(3507ft²)": { minTime: 17.0, maxTime: 19.0 },
      "327m²(3516ft²)": { minTime: 17.0, maxTime: 19.0 },
      "328m²(3526ft²)": { minTime: 17.0, maxTime: 19.0 },
      "329m²(3535ft²)": { minTime: 17.0, maxTime: 19.0 },
      "330m²(3545ft²)": { minTime: 17.0, maxTime: 19.0 },
      "331m²(3554ft²)": { minTime: 17.0, maxTime: 19.0 },
      "332m²(3563ft²)": { minTime: 17.0, maxTime: 19.0 },
      "333m²(3572ft²)": { minTime: 17.0, maxTime: 19.0 },
      "334m²(3582ft²)": { minTime: 17.0, maxTime: 19.0 },
      "335m²(3591ft²)": { minTime: 17.0, maxTime: 19.0 },
      "336m²(3600ft²)": { minTime: 17.0, maxTime: 19.0 },
      "337m²(3610ft²)": { minTime: 17.0, maxTime: 19.0 },
      "338m²(3620ft²)": { minTime: 17.0, maxTime: 19.0 },
      "339m²(3629ft²)": { minTime: 17.0, maxTime: 19.0 },
      "340m²(3638ft²)": { minTime: 17.0, maxTime: 19.0 },
      "341m²(3648ft²)": { minTime: 17.0, maxTime: 19.0 },
      "342m²(3657ft²)": { minTime: 17.0, maxTime: 19.0 },
      "343m²(3667ft²)": { minTime: 17.0, maxTime: 19.0 },
      "344m²(3676ft²)": { minTime: 17.0, maxTime: 19.0 },
      "345m²(3686ft²)": { minTime: 17.0, maxTime: 19.0 },
      "346m²(3695ft²)": { minTime: 17.0, maxTime: 19.0 },
      "347m²(3705ft²)": { minTime: 17.0, maxTime: 19.0 },
      "348m²(3714ft²)": { minTime: 17.0, maxTime: 19.0 },
      "349m²(3724ft²)": { minTime: 17.0, maxTime: 19.0 },
      "350m²(3740ft²)": { minTime: 19.0, maxTime: 4.0 },
      "351m²(3750ft²)": { minTime: 19.0, maxTime: 4.0 },
      "352m²(3760ft²)": { minTime: 19.0, maxTime: 4.0 },
      "353m²(3770ft²)": { minTime: 19.0, maxTime: 4.0 },
      "354m²(3780ft²)": { minTime: 19.0, maxTime: 4.0 },
      "355m²(3790ft²)": { minTime: 19.0, maxTime: 4.0 },
      "356m²(3800ft²)": { minTime: 19.0, maxTime: 4.0 },
      "357m²(3810ft²)": { minTime: 19.0, maxTime: 4.0 },
      "358m²(3820ft²)": { minTime: 19.0, maxTime: 4.0 },
      "359m²(3830ft²)": { minTime: 19.0, maxTime: 4.0 },
      "360m²(3840ft²)": { minTime: 19.0, maxTime: 4.0 },
      "361m²(3850ft²)": { minTime: 19.0, maxTime: 4.0 },
      "362m²(3860ft²)": { minTime: 19.0, maxTime: 4.0 },
      "363m²(3870ft²)": { minTime: 19.0, maxTime: 4.0 },
      "364m²(3880ft²)": { minTime: 19.0, maxTime: 4.0 },
      "365m²(3890ft²)": { minTime: 19.0, maxTime: 4.0 },
      "366m²(3900ft²)": { minTime: 19.0, maxTime: 4.0 },
      "367m²(3910ft²)": { minTime: 19.0, maxTime: 4.0 },
      "368m²(3920ft²)": { minTime: 19.0, maxTime: 4.0 },
      "369m²(3930ft²)": { minTime: 19.0, maxTime: 4.0 },
      "370m²(3940ft²)": { minTime: 19.0, maxTime: 4.0 },
      "371m²(3950ft²)": { minTime: 19.0, maxTime: 4.0 },
      "372m²(3960ft²)": { minTime: 19.0, maxTime: 4.0 },
      "373m²(3970ft²)": { minTime: 19.0, maxTime: 4.0 },
      "374m²(3980ft²)": { minTime: 19.0, maxTime: 4.0 },
      "375m²(4030ft²)": { minTime: 21.0, maxTime: 23.0 },
      "376m²(4040ft²)": { minTime: 21.0, maxTime: 23.0 },
      "377m²(4050ft²)": { minTime: 21.0, maxTime: 23.0 },
      "378m²(4060ft²)": { minTime: 21.0, maxTime: 23.0 },
      "379m²(4070ft²)": { minTime: 21.0, maxTime: 23.0 },
      "380m²(4080ft²)": { minTime: 21.0, maxTime: 23.0 },
      "381m²(4090ft²)": { minTime: 21.0, maxTime: 23.0 },
      "382m²(4100ft²)": { minTime: 21.0, maxTime: 23.0 },
      "383m²(4110ft²)": { minTime: 21.0, maxTime: 23.0 },
      "384m²(4120ft²)": { minTime: 21.0, maxTime: 23.0 },
      "385m²(4130ft²)": { minTime: 21.0, maxTime: 23.0 },
      "386m²(4140ft²)": { minTime: 21.0, maxTime: 23.0 },
      "387m²(4150ft²)": { minTime: 21.0, maxTime: 23.0 },
      "388m²(4160ft²)": { minTime: 21.0, maxTime: 23.0 },
      "389m²(4170ft²)": { minTime: 21.0, maxTime: 23.0 },
      "390m²(4180ft²)": { minTime: 21.0, maxTime: 23.0 },
      "391m²(4190ft²)": { minTime: 21.0, maxTime: 23.0 },
      "392m²(4200ft²)": { minTime: 21.0, maxTime: 23.0 },
      "393m²(4210ft²)": { minTime: 21.0, maxTime: 23.0 },
      "394m²(4220ft²)": { minTime: 21.0, maxTime: 23.0 },
      "395m²(4230ft²)": { minTime: 21.0, maxTime: 23.0 },
      "396m²(4240ft²)": { minTime: 21.0, maxTime: 23.0 },
      "397m²(4250ft²)": { minTime: 21.0, maxTime: 23.0 },
      "398m²(4260ft²)": { minTime: 21.0, maxTime: 23.0 },
      "399m²(4270ft²)": { minTime: 21.0, maxTime: 23.0 },
      "400m²(4300ft²)": { minTime: 23.0, maxTime: 25.0 },
      "401m²(4310ft²)": { minTime: 23.0, maxTime: 25.0 },
      "402m²(4320ft²)": { minTime: 23.0, maxTime: 25.0 },
      "403m²(4330ft²)": { minTime: 23.0, maxTime: 25.0 },
      "404m²(4340ft²)": { minTime: 23.0, maxTime: 25.0 },
      "405m²(4350ft²)": { minTime: 23.0, maxTime: 25.0 },
      "406m²(4360ft²)": { minTime: 23.0, maxTime: 25.0 },
      "407m²(4370ft²)": { minTime: 23.0, maxTime: 25.0 },
      "408m²(4380ft²)": { minTime: 23.0, maxTime: 25.0 },
      "409m²(4390ft²)": { minTime: 23.0, maxTime: 25.0 },
      "410m²(4400ft²)": { minTime: 23.0, maxTime: 25.0 },
      "411m²(4410ft²)": { minTime: 23.0, maxTime: 25.0 },
      "412m²(4420ft²)": { minTime: 23.0, maxTime: 25.0 },
      "413m²(4430ft²)": { minTime: 23.0, maxTime: 25.0 },
      "414m²(4440ft²)": { minTime: 23.0, maxTime: 25.0 },
      "415m²(4450ft²)": { minTime: 23.0, maxTime: 25.0 },
      "416m²(4460ft²)": { minTime: 23.0, maxTime: 25.0 },
      "417m²(4470ft²)": { minTime: 23.0, maxTime: 25.0 },
      "418m²(4480ft²)": { minTime: 23.0, maxTime: 25.0 },
      "419m²(4490ft²)": { minTime: 23.0, maxTime: 25.0 },
      "420m²(4500ft²)": { minTime: 23.0, maxTime: 25.0 },
      "421m²(4510ft²)": { minTime: 23.0, maxTime: 25.0 },
      "422m²(4520ft²)": { minTime: 23.0, maxTime: 25.0 },
      "423m²(4530ft²)": { minTime: 23.0, maxTime: 25.0 },
      "424m²(4540ft²)": { minTime: 23.0, maxTime: 25.0 },
      "425m²(4570ft²)": { minTime: 25.0, maxTime: 27.0 },
      "426m²(4580ft²)": { minTime: 25.0, maxTime: 27.0 },
      "427m²(4590ft²)": { minTime: 25.0, maxTime: 27.0 },
      "428m²(4600ft²)": { minTime: 25.0, maxTime: 27.0 },
      "429m²(4610ft²)": { minTime: 25.0, maxTime: 27.0 },
      "430m²(4620ft²)": { minTime: 25.0, maxTime: 27.0 },
      "431m²(4630ft²)": { minTime: 25.0, maxTime: 27.0 },
      "432m²(4640ft²)": { minTime: 25.0, maxTime: 27.0 },
      "433m²(4650ft²)": { minTime: 25.0, maxTime: 27.0 },
      "434m²(4660ft²)": { minTime: 25.0, maxTime: 27.0 },
      "435m²(4670ft²)": { minTime: 25.0, maxTime: 27.0 },
      "436m²(4680ft²)": { minTime: 25.0, maxTime: 27.0 },
      "437m²(4690ft²)": { minTime: 25.0, maxTime: 27.0 },
      "438m²(4700ft²)": { minTime: 25.0, maxTime: 27.0 },
      "439m²(4710ft²)": { minTime: 25.0, maxTime: 27.0 },
      "440m²(4720ft²)": { minTime: 25.0, maxTime: 27.0 },
      "441m²(4730ft²)": { minTime: 25.0, maxTime: 27.0 },
      "442m²(4740ft²)": { minTime: 25.0, maxTime: 27.0 },
      "443m²(4750ft²)": { minTime: 25.0, maxTime: 27.0 },
      "444m²(4760ft²)": { minTime: 25.0, maxTime: 27.0 },
      "445m²(4770ft²)": { minTime: 25.0, maxTime: 27.0 },
      "446m²(4780ft²)": { minTime: 25.0, maxTime: 27.0 },
      "447m²(4790ft²)": { minTime: 25.0, maxTime: 27.0 },
      "448m²(4800ft²)": { minTime: 25.0, maxTime: 27.0 },
      "449m²(4810ft²)": { minTime: 25.0, maxTime: 27.0 },

      "450m²(4840ft²)": { minTime: 27.0, maxTime: 29.0 },
      "451m²(4850ft²)": { minTime: 27.0, maxTime: 29.0 },
      "452m²(4860ft²)": { minTime: 27.0, maxTime: 29.0 },
      "453m²(4870ft²)": { minTime: 27.0, maxTime: 29.0 },
      "454m²(4880ft²)": { minTime: 27.0, maxTime: 29.0 },
      "455m²(4890ft²)": { minTime: 27.0, maxTime: 29.0 },
      "456m²(4900ft²)": { minTime: 27.0, maxTime: 29.0 },
      "457m²(4910ft²)": { minTime: 27.0, maxTime: 29.0 },
      "458m²(4920ft²)": { minTime: 27.0, maxTime: 29.0 },
      "459m²(4930ft²)": { minTime: 27.0, maxTime: 29.0 },
      "460m²(4940ft²)": { minTime: 27.0, maxTime: 29.0 },
      "461m²(4950ft²)": { minTime: 27.0, maxTime: 29.0 },
      "462m²(4960ft²)": { minTime: 27.0, maxTime: 29.0 },
      "463m²(4970ft²)": { minTime: 27.0, maxTime: 29.0 },
      "464m²(4980ft²)": { minTime: 27.0, maxTime: 29.0 },
      "465m²(4990ft²)": { minTime: 27.0, maxTime: 29.0 },
      "466m²(5000ft²)": { minTime: 27.0, maxTime: 29.0 },
      "467m²(5010ft²)": { minTime: 27.0, maxTime: 29.0 },
      "468m²(5020ft²)": { minTime: 27.0, maxTime: 29.0 },
      "469m²(5030ft²)": { minTime: 27.0, maxTime: 29.0 },
      "470m²(5040ft²)": { minTime: 27.0, maxTime: 29.0 },
      "471m²(5050ft²)": { minTime: 27.0, maxTime: 29.0 },
      "472m²(5060ft²)": { minTime: 27.0, maxTime: 29.0 },
      "473m²(5070ft²)": { minTime: 27.0, maxTime: 29.0 },
      "474m²(5080ft²)": { minTime: 27.0, maxTime: 29.0 },

      "475m²(5110ft²)": { minTime: 29.0, maxTime: 32.0 },
      "476m²(5120ft²)": { minTime: 29.0, maxTime: 32.0 },
      "477m²(5130ft²)": { minTime: 29.0, maxTime: 32.0 },
      "478m²(5140ft²)": { minTime: 29.0, maxTime: 32.0 },
      "479m²(5150ft²)": { minTime: 29.0, maxTime: 32.0 },
      "480m²(5160ft²)": { minTime: 29.0, maxTime: 32.0 },
      "481m²(5170ft²)": { minTime: 29.0, maxTime: 32.0 },
      "482m²(5180ft²)": { minTime: 29.0, maxTime: 32.0 },
      "483m²(5190ft²)": { minTime: 29.0, maxTime: 32.0 },
      "484m²(5200ft²)": { minTime: 29.0, maxTime: 32.0 },
      "485m²(5210ft²)": { minTime: 29.0, maxTime: 32.0 },
      "486m²(5220ft²)": { minTime: 29.0, maxTime: 32.0 },
      "487m²(5230ft²)": { minTime: 29.0, maxTime: 32.0 },
      "488m²(5240ft²)": { minTime: 29.0, maxTime: 32.0 },
      "489m²(5250ft²)": { minTime: 29.0, maxTime: 32.0 },
      "490m²(5260ft²)": { minTime: 29.0, maxTime: 32.0 },
      "491m²(5270ft²)": { minTime: 29.0, maxTime: 32.0 },
      "492m²(5280ft²)": { minTime: 29.0, maxTime: 32.0 },
      "493m²(5290ft²)": { minTime: 29.0, maxTime: 32.0 },
      "494m²(5300ft²)": { minTime: 29.0, maxTime: 32.0 },
      "495m²(5310ft²)": { minTime: 29.0, maxTime: 32.0 },
      "496m²(5320ft²)": { minTime: 29.0, maxTime: 32.0 },
      "497m²(5330ft²)": { minTime: 29.0, maxTime: 32.0 },
      "498m²(5340ft²)": { minTime: 29.0, maxTime: 32.0 },
      "499m²(5350ft²)": { minTime: 29.0, maxTime: 32.0 },
      "500m²(5360ft²)": { minTime: 29.0, maxTime: 32.0 },
    };

  // Predefined cleaners based on the duration range
  const cleanersMapping: Record<string, number> = {
    "2.30 - 3.00 hours": 1,
    "3.00 - 4.00 hours": 1,
    "4.00 - 5.30 hours": 1,
    "5.30 - 6.30 hours": 1,
    "6.30 - 7.30 hours": 1,
    "7.30 - 9.00 hours": 2,
    "9.00 - 10.30 hours": 2,
    "10.30 - 12.00 hours": 2,
    "12.00 - 13.30 hours": 2,
    "13.30 - 15.30 hours": 2,
    "15.30 - 17.00 hours": 3,
    "17.00 - 19.00 hours": 3,
    "19.00 - 21.00 hours": 3,
    "21.00 - 23.00 hours": 4,
    "23.00 - 25.00 hours": 4,
    "25.00 - 27.00 hours": 4,
    "27.00 - 29.00 hours": 5,
    "29.00 - 32.00 hours": 5,
  };

  const formatTime = (time: number) => {
    const hours = Math.floor(time);
    const minutes = Math.round((time - hours) * 60);
    const formattedMinutes = minutes < 10 ? `0${minutes}` : minutes;
    return `${hours}.${formattedMinutes}`;
  };

  useEffect(() => {
    if (propertySize) {
      setIsPropertySizeSelected(true); // Mark property size as selected
      const matchedDuration = durationMapping[propertySize];

      if (matchedDuration) {
        const formattedMinTime = formatTime(matchedDuration.minTime);
        const formattedMaxTime = formatTime(matchedDuration.maxTime);

        const formattedDuration = `${formattedMinTime} - ${formattedMaxTime} hours`;
        setDuration(formattedDuration);

        // Auto-generate the number of cleaners based on the generated duration
        const cleanersKey = `${formattedMinTime} - ${formattedMaxTime} hours`;
        const generatedCleaners = cleanersMapping[cleanersKey] || 1; // default to 1 cleaner if no match

        // Only update numCleaners if the user hasn't manually changed it
        if (!isManualCleanerChange) {
          setNumCleaners(generatedCleaners.toString());
        }

        // Set autoGeneratedCleaners value for the dropdown
        setAutoGeneratedCleaners(generatedCleaners);

        // Pass maxTime to parent component for base price calculation
        onBasePriceChange(matchedDuration.maxTime);
      }
    }
  }, [propertySize, isManualCleanerChange, onBasePriceChange]);

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
      <Dropdown
        label="Approx. Property Size"
        value={propertySize}
        options={Object.keys(durationMapping).map((size) => ({
          value: size,
          label: size,
        }))}
        onChange={setPropertySize}
      />
      {/* Time Duration for Work Dropdown */}
      <div>
        <Dropdown
          label="Time Duration for Work (Auto-suggested)"
          value={duration}
          type="text"
          onChange={setDuration}
          readOnly
          placeholder="Auto-suggested / Hours : minutes"
        />
        {/* Add the message below the dropdown */}

        {propertySize && (
          <div className="text-sm text-blue-500   px-1">
            <InfoIcon sx={{ color: "black", mx: 1 }} />
            Depending on your space's conditions, the cleaning duration will be
            decreased or extended.
          </div>
        )}
      </div>

      {/* Custom Input for Number of Cleaners */}
      <div className="flex flex-col gap-2">
        <label className="block mb-2 text-blue-900">
          Number of Cleaners (Auto-suggested, Editable)
        </label>
        <div className="flex items-center gap-2">
          <input
            type="number"
            value={numCleaners}
            onChange={(e) => {
              const value = Math.max(1, Math.min(5, Number(e.target.value)));
              setNumCleaners(value.toString());
              setIsManualCleanerChange(true); // Mark as manually changed
            }}
            className="w-full p-2 border border-gray-500 rounded-lg text-center text-black"
            min={1}
            max={5}
          />
          <div
            className="p-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
            onClick={() => {
              setNumCleaners(Math.max(1, Number(numCleaners) - 1).toString());
              setIsManualCleanerChange(true); // Mark as manually changed
            }}
          >
            <FaMinus />
          </div>
          <div
            className="p-2 bg-blue-900 text-white rounded-lg hover:bg-blue-950 transition-colors"
            onClick={() => {
              setNumCleaners(Math.min(5, Number(numCleaners) + 1).toString());
              setIsManualCleanerChange(true); // Mark as manually changed
            }}
          >
            <FaPlus />
          </div>
        </div>
        <div>
          {isPropertySizeSelected &&
            autoGeneratedCleaners !== Number(numCleaners) && (
              <span className="text-sm text-black-500">
                <span className="font-semibold"></span> suggested cleaners:{" "}
                {autoGeneratedCleaners}
              </span>
            )}
        </div>
      </div>

      <Dropdown
        label="Select your business or property"
        value={propertyType}
        options={propertyTypeOptions}
        onChange={setPropertyType}
      />

      <Dropdown
        label="Gender Required"
        value={contactType}
        options={contactTypeOptions}
        onChange={setContactType}
      />
      <Dropdown
        label="Select Language"
        value={language}
        options={languageOptions}
        onChange={setLanguage}
      />
    </div>
  );
};

export default BookingSectionCart;
